# Generated by Django 3.1.3 on 2020-11-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('cmp_class_name', models.CharField(max_length=100)),
                ('cmp_class_xpath', models.CharField(max_length=100)),
                ('cmp_allow_button_name', models.CharField(max_length=100)),
                ('cmp_allow_button_xpath', models.CharField(max_length=100)),
            ],
        ),
    ]
